version: '3.8'

services:
  auth:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=supersecretkey
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 